### ISSUE TITLE
brpc只能使用protobuf吗？如果我想使用flatbuffer，能支持吗

### ISSUE THREAD

**Issue by Funlxy** [apache/brpc#2354]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by zhoumo02** [comment]
你好！
brpc在百度公司内部已经有支持flatbuffers的版本，经过我们的测试，性能能提升20%以上。
目前仍然在试验阶段，尚未大规模使用，暂时还没有开源的计划

谢谢！

**Comment by Funlxy** [comment]
> 你好！ brpc在百度公司内部已经有支持flatbuffers的版本，经过我们的测试，性能能提升20%以上。 目前仍然在试验阶段，尚未大规模使用，暂时还没有开源的计划
> 
> 谢谢！

谢谢回答！

**Comment by xiangpdu** [comment]
@zhoumo02  请问下这个功能目前还是没有开源的计划吗？

**Comment by Aleda** [comment]
目前bRPC flatbuffer版本在百度已经有初步有了一些部署规模，目前比较稳定。由于需要前后端统一改造后生效，我们的想法是继续在某个重要业务上灰度至70%之后启动开源至upstream，我觉得这个时间可能在24年底左右，请耐心等待，谢谢。
The bRPC flatbuffer version has already been deployed on a initial scale within Baidu and is currently quite stable. Since it requires coordinated changes on both the frontend and backend to take effect, our plan is to continue rolling out a gray release on a important service until reaching 70% deployment, after which we will do the open-sourcing to upstream. I anticipate this will likely happen around the end of 2024. Please be patient. Thank you.
@xiangpdu

**Comment by lintanghui** [comment]
开源计划进度有更新嘛

**Comment by egolearner** [comment]
Hi @Aleda ，flatbuffer有开源计划了吗？

**Comment by AnDiXL** [comment]
> 你好[@Aleda](https://github.com/Aleda)，flatbuffer有开源计划了吗？

你好，我们已经在梳理开源代码与内部代码的差异了，预计今年底前会将brpc接入flatbuffers的代码开源出来
